### ISSUE TITLE
Could not find module 'libcudart.so' (or one of its dependencies). Try using the full path with constructor syntax. 

### ISSUE THREAD

**Issue by maxmelichov** [onnx/onnx-tensorrt#951]
## Description

I'm getting Could not find module 'libcudart.so' (or one of its dependencies). Try using the full path with constructor syntax. when trying to run python setup.py install

**TensorRT Version**: 8.6.1
**GPU Type**:  GTX 1060/ GTX 1660 Ti
**Nvidia Driver Version**: 546.33
**CUDA Version**: 11.8
**CUDNN Version**: 8.6.0.163 
**Operating System + Version**: win10 
**Python Version (if applicable)**: 3.10.2
**TensorFlow + TF2ONNX Version (if applicable)**: tensorflow == 2.13.0rc1
**PyTorch Version (if applicable)**: torch  2.1.2+cu118

**Comment by idaoi** [comment]
在 Windows 10 上，没有 libcudart.so 这个文件，你可以用cudart64_XX.dll 文件，其中 XX 是 CUDA 版本号

**Comment by idaoi** [comment]
在 Windows 10 上，没有 libcudart.so 这个文件，你可以用cudart64_XX.dll 文件，其中 XX 是 CUDA 版本号
On Windows 10, the libcudart.so file is not available. You can use the cudart64_XX.dll file, where XX is the CUDA version number

**Comment by maxmelichov** [comment]
> 在 Windows 10 上，没有 libcudart.so 这个文件，你可以用cudart64_XX.dll 文件，其中 XX 是 CUDA 版本号 On Windows 10, the libcudart.so file is not available. You can use the cudart64_XX.dll file, where XX is the CUDA version number

and how do I use cudart64_XX.dll?

**Comment by idaoi** [comment]
Thank you. A few months ago, I resolved this issue.I seem to have replaced&nbsp;“libcuda.so”&nbsp;with&nbsp;“cudart.dll&nbsp; or nvcuda.dll”.&nbsp;It's been a bit long, I forgot which file I specifically used.Sorry for not closing this issue in a timely manner. Thank you very much for your reply.&nbsp;


@*$%&amp;=
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maxim ***@***.***&gt;; 
发送时间: 2024年9月8日(星期天) 晚上8:37
收件人: ***@***.***&gt;; 
抄送: "@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [onnx/onnx-tensorrt] Could not find module &#39;libcudart.so&#39; (or one of its dependencies). Try using the full path with constructor syntax.  (Issue #951)















在Windows 10上，没有libcuda.so这个文件，你可以用cuda 64_XX.dll文件，其中XX是CUDA版本号在Windows 10上，libcuda.so文件不可用。您可以使用cudart64_XX.dll文件，其中XX是CUDA版本号

以及如何使用cudart64_XX.dll

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by maxmelichov** [comment]
I opened the issue...
and did something else in time, but now I have returned to it and am still facing the same issue.
Can you help me? I have no idea what you said right now

**Comment by idaoi** [comment]
> 我打开了这个问题…… 并及时做了其他事情，但现在我又回到了这个问题，仍然面临同样的问题。 你能帮我吗？我不知道你现在说了什么。
我记着我当时是找到”torch“报错的位置，将”torch"源文件中的 “libcudart.so” 替换为 “cudart64_XX.dll”,

**Comment by maxmelichov** [comment]
damn, is there a more simple way to run the inference trt file on Windows (moved to win11)

**Comment by idaoi** [comment]
> 该死，有没有更简单的方法在 Windows 上运行推理 trt 文件（移至 win11）
Sorry, I don't know about that. But you can search for "cudart6464" in the CUDA installation folder to find the specific file name, such as "cudart64_102. dll", and then modify the location mentioned in the picture.

![VGI0A4WB@M9UZ0E~7 U P%F](https://github.com/user-attachments/assets/9ed53023-0bb1-493a-838f-099f20a634c0)

![%DG5(6GO03Z0JHK0ON6CQ@W](https://github.com/user-attachments/assets/e301820f-d117-45cf-9c29-d3d4b3cb98e0)

**Comment by maxmelichov** [comment]
King!
I will check that thanks!

**Comment by qwerzjut** [comment]
Have you solved this problem？
